name = "GABG's XVanilla"
author = "GABG"
version = "3.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53968d0a9c74807e4996d8aec89ffe01ffaa87482263ae6b11a93d117200aa60"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
