name = "GABG's XVanilla"
author = "GABG"
version = "3.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24913841f96478a917ad619c2b9dff3acacf003d842a88297e4714004a52a688"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
