name = "GABG's XVanilla"
author = "GABG"
version = "3.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56228aaae44e173da47a4400c5de40614d74a449c5264368938fb5d5d60ec194"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
