name: Release new version

on:
  push:
    tags:
      - "v*.*.*"


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packwiz
        run: |
          curl -Lo packwiz.zip "https://nightly.link/gandbg/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip"
          unzip packwiz.zip
          chmod +x ./packwiz

      - name: Build package
        run: ./packwiz modrinth export

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: modrinth-package
          path: "*.mrpack"
          compression-level: 0

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.mrpack"
          draft: true
